services:
  app:
    build: .
    ports:
      - "0.0.0.0:8080:8080" #Anyone can access it 
    env_file:
      - .env          # loads all your DB_* variables from the .env file
    restart: unless-stopped
